export const obdProviders = [
  {
    name: 'Bouncie',
    hardware: 'Bouncie OBD2 GPS tracker',
    fit: 'Recommended first',
    coverage: 'Most passenger vehicles with an OBD2 port, generally 1996 and newer',
    data: 'Live and trip locations, speed, trips, battery, MIL alerts, geo-zones',
    integration: 'OAuth 2.0, REST API, and authenticated webhooks',
    status: 'Adapter ready — credentials required',
    url: 'https://docs.bouncie.dev/',
  },
  {
    name: 'Zubie',
    hardware: 'Zubie OBD-II GPS device',
    fit: 'Rental fleet ready',
    coverage: 'Most cars, vans, and light-duty trucks with OBD-II',
    data: 'Real-time location, trip points, odometer, fuel, battery, diagnostics',
    integration: 'Zinc OAuth 2.0, REST API, and webhooks',
    status: 'Provider adapter planned',
    url: 'https://developer.zubie.com/overview/getting-started',
  },
  {
    name: 'Geotab',
    hardware: 'GO9 and supported GO devices',
    fit: 'Enterprise fleets',
    coverage: 'OBD2, CAN, J1939, and additional vehicle protocols',
    data: 'GPS, speed, accelerometer, engine health, fuel, faults, odometer',
    integration: 'MyGeotab API and data feeds',
    status: 'Enterprise adapter planned',
    url: 'https://developers.geotab.com/myGeotab/apiReference/objects/Device/index.html',
  },
  {
    name: 'Samsara',
    hardware: 'VG34 and VG54 vehicle gateways',
    fit: 'Enterprise fleets',
    coverage: 'Passenger, light-duty, and commercial vehicles with supported cables',
    data: 'GPS, routes, speed, engine state, fuel, fault codes, OBD odometer',
    integration: 'Scoped API tokens, REST feeds, routes, and webhooks',
    status: 'Enterprise adapter planned',
    url: 'https://developers.samsara.com/docs/telematics',
  },
];
